version: "3.3"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - ${IP}:4000:80
    volumes:
      - ./content:/var/www/html/wp-content
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}
      - wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DEBUG: 1
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - ${IP}:4001:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default_authentication_plugin=mysql_native_password",
      ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${IP}:4002:80
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: "${DB_PASSWORD}"
      PMA_PORT: 3306
      PMA_USER: root
    depends_on:
      - mysql
      - wordpress
    links:
      - mysql

volumes:
  mysql_data: {}
  wordpress_data: {}
